// <auto-generated />
using System;
using INSCRIPCION_ESTUDIANTIL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace INSCRIPCION_ESTUDIANTIL.Migrations
{
    [DbContext(typeof(DbproyectoContext))]
    [Migration("20231124162011_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("INSCRIPCION_ESTUDIANTIL.Models.Asignatura", b =>
                {
                    b.Property<int>("IdAsignaturas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_ASIGNATURAS");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsignaturas"));

                    b.Property<int?>("Creditos")
                        .HasColumnType("int")
                        .HasColumnName("CREDITOS");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DESCRIPCION");

                    b.Property<string>("NombreAsignatura")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("NOMBRE_ASIGNATURA");

                    b.HasKey("IdAsignaturas")
                        .HasName("PK__ASIGNATU__138FA4E4796D614A");

                    b.ToTable("ASIGNATURAS", (string)null);
                });

            modelBuilder.Entity("INSCRIPCION_ESTUDIANTIL.Models.Curso", b =>
                {
                    b.Property<int>("IdCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_CURSO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCurso"));

                    b.Property<string>("DescripcionCurso")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DESCRIPCION_CURSO");

                    b.Property<string>("NombreCurso")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("NOMBRE_CURSO");

                    b.HasKey("IdCurso")
                        .HasName("PK__CURSO__9B4AE79840085B5F");

                    b.ToTable("CURSO", (string)null);
                });

            modelBuilder.Entity("INSCRIPCION_ESTUDIANTIL.Models.Inscripcion", b =>
                {
                    b.Property<int>("IdInscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_INSCRIPCION");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInscripcion"));

                    b.Property<string>("EstadoInscripcion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ESTADO_INSCRIPCION");

                    b.Property<DateTime?>("FechaInscripcion")
                        .HasColumnType("date")
                        .HasColumnName("FECHA_INSCRIPCION");

                    b.Property<int?>("IdCurso")
                        .HasColumnType("int")
                        .HasColumnName("ID_CURSO");

                    b.Property<string>("IdEstudiante")
                        .HasMaxLength(9)
                        .IsUnicode(false)
                        .HasColumnType("varchar(9)")
                        .HasColumnName("ID_ESTUDIANTE");

                    b.HasKey("IdInscripcion")
                        .HasName("PK__INSCRIPC__28EB027EB76FB055");

                    b.HasIndex("IdCurso");

                    b.ToTable("INSCRIPCION", (string)null);
                });

            modelBuilder.Entity("INSCRIPCION_ESTUDIANTIL.Models.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_PAGO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("date")
                        .HasColumnName("FECHA_PAGO");

                    b.Property<int?>("IdInscripcion")
                        .HasColumnType("int")
                        .HasColumnName("ID_INSCRIPCION");

                    b.Property<double?>("Monto")
                        .HasColumnType("float")
                        .HasColumnName("MONTO");

                    b.HasKey("IdPago")
                        .HasName("PK__PAGOS__B68D23DF2BEA63D3");

                    b.HasIndex("IdInscripcion");

                    b.ToTable("PAGOS", (string)null);
                });

            modelBuilder.Entity("INSCRIPCION_ESTUDIANTIL.Models.Profesore", b =>
                {
                    b.Property<int>("IdProfesor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_PROFESOR");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProfesor"));

                    b.Property<string>("CorreoProfesor")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CORREO_PROFESOR");

                    b.Property<int?>("IdAsignaturas")
                        .HasColumnType("int")
                        .HasColumnName("ID_ASIGNATURAS");

                    b.Property<int?>("IdSecciones")
                        .HasColumnType("int")
                        .HasColumnName("ID_SECCIONES");

                    b.Property<string>("NombreProfesor")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("NOMBRE_PROFESOR");

                    b.HasKey("IdProfesor")
                        .HasName("PK__PROFESOR__5D30231FC2E4B858");

                    b.HasIndex("IdAsignaturas");

                    b.HasIndex("IdSecciones");

                    b.ToTable("PROFESORES", (string)null);
                });

            modelBuilder.Entity("INSCRIPCION_ESTUDIANTIL.Models.Seccione", b =>
                {
                    b.Property<int>("IdSecciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_SECCIONES");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSecciones"));

                    b.Property<int?>("CuposSeccion")
                        .HasColumnType("int")
                        .HasColumnName("CUPOS_SECCION");

                    b.Property<int?>("IdCurso")
                        .HasColumnType("int")
                        .HasColumnName("ID_CURSO");

                    b.Property<string>("NombreSeccion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NOMBRE_SECCION");

                    b.HasKey("IdSecciones")
                        .HasName("PK__SECCIONE__4A6892CA12E1BC28");

                    b.HasIndex("IdCurso");

                    b.ToTable("SECCIONES", (string)null);
                });

            modelBuilder.Entity("INSCRIPCION_ESTUDIANTIL.Models.Inscripcion", b =>
                {
                    b.HasOne("INSCRIPCION_ESTUDIANTIL.Models.Curso", "oCurso")
                        .WithMany("Inscripcions")
                        .HasForeignKey("IdCurso")
                        .HasConstraintName("FK_CURSO");

                    b.Navigation("oCurso");
                });

            modelBuilder.Entity("INSCRIPCION_ESTUDIANTIL.Models.Pago", b =>
                {
                    b.HasOne("INSCRIPCION_ESTUDIANTIL.Models.Inscripcion", "oInscripcion")
                        .WithMany("Pagos")
                        .HasForeignKey("IdInscripcion")
                        .HasConstraintName("FK_INSCRIPCION");

                    b.Navigation("oInscripcion");
                });

            modelBuilder.Entity("INSCRIPCION_ESTUDIANTIL.Models.Profesore", b =>
                {
                    b.HasOne("INSCRIPCION_ESTUDIANTIL.Models.Asignatura", "oAsignatura")
                        .WithMany("Profesores")
                        .HasForeignKey("IdAsignaturas")
                        .HasConstraintName("FK_ASIGNATURA");

                    b.HasOne("INSCRIPCION_ESTUDIANTIL.Models.Seccione", "oSecciones")
                        .WithMany("Profesores")
                        .HasForeignKey("IdSecciones")
                        .HasConstraintName("FK_SECCIONES");

                    b.Navigation("oAsignatura");

                    b.Navigation("oSecciones");
                });

            modelBuilder.Entity("INSCRIPCION_ESTUDIANTIL.Models.Seccione", b =>
                {
                    b.HasOne("INSCRIPCION_ESTUDIANTIL.Models.Curso", "oCurso")
                        .WithMany("Secciones")
                        .HasForeignKey("IdCurso")
                        .HasConstraintName("FK_CURSO_SECCIONES");

                    b.Navigation("oCurso");
                });

            modelBuilder.Entity("INSCRIPCION_ESTUDIANTIL.Models.Asignatura", b =>
                {
                    b.Navigation("Profesores");
                });

            modelBuilder.Entity("INSCRIPCION_ESTUDIANTIL.Models.Curso", b =>
                {
                    b.Navigation("Inscripcions");

                    b.Navigation("Secciones");
                });

            modelBuilder.Entity("INSCRIPCION_ESTUDIANTIL.Models.Inscripcion", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("INSCRIPCION_ESTUDIANTIL.Models.Seccione", b =>
                {
                    b.Navigation("Profesores");
                });
#pragma warning restore 612, 618
        }
    }
}
